version: 0.1.{build}
image: Visual Studio 2019
before_build:
- choco install opencover.portable
- choco install codecov
- cmd: >-
    dotnet restor
build_script:
- cmd: >-
    dotnet build SharpNES.standard -c Release
test_script:
- cmd: >-
    dotnet test SharpNES.standard.test
after_test:
  - OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full ./SharpNES.standard.test/SharpNES.standard.csproj" -output:".\my_app_coverage.xml"
  - codecov -f .\valit_coverage.xml -t $(codecov_token)